[simulation]
name = "f1_eta95"
start = "2026-01-06 13:30"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.95/VBbounds_f1_e572kWh_p350kW_eta95.csv"

[optimization.depot]
eta_grid2depot = 0.95
eta_depot2grid = 0.95
