[simulation]
name = "f1_eta94"
start = "2026-01-06 13:30"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.94/VBbounds_f1_e572kWh_p150kW_eta94.csv"

[optimization.depot]
eta_grid2depot = 0.94
eta_depot2grid = 0.94
