[simulation]
name = "f2_eta100"
start = "2026-01-01 08:30"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_1.00/VBbounds_f2_e572kWh_p350kW_eta100.csv"

[optimization.depot]
eta_grid2depot = 1.0
eta_depot2grid = 1.0
