[simulation]
name = "f3_eta99"
start = "2026-01-06 12:45"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.99/VBbounds_f3_e572kWh_p150kW_eta99.csv"

[optimization.depot]
eta_grid2depot = 0.99
eta_depot2grid = 0.99
