[simulation]
name = "f4_eta91"
start = "2026-01-07 07:15"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.91/VBbounds_f4_e572kWh_p350kW_eta91.csv"

[optimization.depot]
eta_grid2depot = 0.91
eta_depot2grid = 0.91
