[simulation]
name = "f5_eta94"
start = "2026-01-07 20:45"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.94/VBbounds_f5_e572kWh_p350kW_eta94.csv"

[optimization.depot]
eta_grid2depot = 0.94
eta_depot2grid = 0.94
