[simulation]
name = "f5_eta92"
start = "2026-01-07 20:45"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_0.92/VBbounds_f5_e572kWh_p150kW_eta92.csv"

[optimization.depot]
eta_grid2depot = 0.92
eta_depot2grid = 0.92
