[simulation]
name = "f6_eta100"
start = "2026-01-06 07:45"
end = "2026-03-25 23:45"

[optimization.flexibility]
bounds_file = "data/flexibility/efficiency/eta_1.00/VBbounds_f6_e572kWh_p150kW_eta100.csv"

[optimization.depot]
eta_grid2depot = 1.0
eta_depot2grid = 1.0
