simulation:
  start: "2025-10-01 00:00"                                 # simulation start
  end: "2025-10-5 23:45"                                    # simulation end
  timestep_hours: 0.25                                      # simulation timestep

optimization:
  mode: joint
  markets:
    dayahead:
      enabled: true
      source: "data/prices/prices_DA_example.csv"
      fee_eur_per_mwh: 0.02                                 # €/MWh (clearing fee + exchange fee + broker fee + ...)
    intraday:
      enabled: true
      source: "data/prices/prices_IDC_example.csv"
      fee_eur_per_mwh: 0.03                                 # €/MWh (clearing fee + exchange fee + broker fee + ...)

  trading:
    mode: "realistic"   # "none", "realistic"
    dayahead:
      gate_closure_hour: "12:00"                # D-1
      closes_previous_day: true
    intraday:
      offset_minutes_before_delivery: 5       # trading until T-30min

  imbalance:
    enabled: true
    only_on_infeasible: true
    source_pos: "data/prices/prices_reBAPpos_example.csv"
    source_neg: "data/prices/prices_reBAPneg_example.csv"
    imbalance_volume_penalty_eur_per_kwh: 1000

  virtual_arbitrage: false

  degradation:
    enabled: true
    cost_eur_per_mwh_throughput: 20.0

  mpc:
    enabled: true
    da_horizon_hours: 48
    id_horizon_hours: 1
    terminal_condition: true
    terminal_weight_eur_per_kwh: 50

  mobility:
    enabled: true
    bounds_file: "data/mobility/vb_bounds_example.csv"

optimize:
  out: "results/dispatch.csv"
  vehicle:
    eta_charge: 0.95
    eta_discharge: 0.95
  site:
    grid_connection_limit: 10000

plot:
  dispatch: "results/dispatch.csv"
  out: "results/dispatch.html"
  cashflow_out: "results/cashflows.html"
  open: true


