simulation:
  start: "2025-10-01 00:00"                                 # simulation start
  end: "2025-10-3 23:45"                                   # simulation end
  timestep_hours: 0.25                                      # simulation timestep
  out_dispatch: "results/dispatch_example"
  out_commit: "results/commit_example"

optimization:
  markets:
    dayahead:
      enabled: true                                         # "true", "false"
      source: "data/prices/prices_DA_example.csv"
      fee_eur_per_kwh: 0.005                                # €/kWh (clearing fee + exchange fee + broker fee + ...)
    intraday:
      enabled: true                                         # "true", "false"
      source: "data/prices/prices_IDC_example.csv"
      fee_eur_per_kwh: 0.008                                # €/kWh (clearing fee + exchange fee + broker fee + ...)

  trading:
    mode: "realistic"                                       # "none", "realistic"
    dayahead:
      gate_closure_hour: "12:00"
      closes_previous_day: true                             # "true" = D-1, "false" = D
    intraday:
      offset_minutes_before_delivery: 5                     # trading until T-5min

  imbalance:
    enabled: true                                           # "true", "false"
    only_on_infeasible: true                                # "true", "false"
    source_pos: "data/prices/prices_reBAPpos_example.csv"
    source_neg: "data/prices/prices_reBAPneg_example.csv"
    imbalance_volume_penalty_eur_per_kwh: 1000              # €/kWh

  virtual_arbitrage: false                                  # "true", "false"

  mpc:
    da_horizon_hours: 48                                    # length of DA prediction horizon in hours
    id_horizon_hours: 1                                     # length of DA prediction horizon in hours
    terminal_condition: true                                # "true", "false"
    terminal_weight_eur_per_kwh: 50                         # €/kWh

  flexibility:
    bounds_file: "data/flexibility/vb_bounds_example.csv"
    cycle_regularization:
      enabled: true
      cost_eur_per_kwh_throughput: 0.02                     # €/kWh

  depot:
    eta_grid2depot : 1.0                                    # efficiency import
    eta_depot2grid : 1.0                                    # efficiency export
    grid_connection_limit: 10000                            # grid connection limit in kWp



