[simulation]
name = "f2_da_id"
start = "2026-01-01 08:30"
end = "2026-03-25 23:45"

[optimization.markets.intraday]
enabled = true

[optimization.trading.fcr]
enabled = false

[optimization.flexibility]
bounds_file = "data/flexibility/market/VBbounds_f2_e572kWh_p150kW_eta98.csv"
