[simulation]
name = "f2_da_uni"
start = "2026-01-01 08:30"
end = "2026-05-31 23:45"

[optimization.markets.intraday]
enabled = false

[optimization.trading.fcr]
enabled = false

[optimization.flexibility]
bounds_file = "data/flexibility/market/unidirectional/VBbounds_f2_e572kWh_p150kW_eta98.csv"
