[simulation]
name = "f3_da_id_fcr"
start = "2026-01-06 12:45"
end = "2026-02-06 12:45"

[optimization.markets.intraday]
enabled = true

[optimization.trading.fcr]
enabled = true

[optimization.flexibility]
bounds_file = "data/flexibility/market/VBbounds_f3_e572kWh_p350kW_eta98.csv"
