[simulation]
name = "f4_da_id_fcr"
start = "2026-01-07 07:15"
end = "2026-05-31 23:45"

[optimization.markets.intraday]
enabled = true

[optimization.trading.fcr]
enabled = true

[optimization.flexibility]
bounds_file = "data/flexibility/market/VBbounds_f4_e572kWh_p150kW_eta98.csv"
