[simulation]
name = "f5_da"
start = "2026-01-07 20:45"
end = "2026-05-31 23:45"

[optimization.markets.intraday]
enabled = false

[optimization.trading.fcr]
enabled = false

[optimization.flexibility]
bounds_file = "data/flexibility/market/VBbounds_f5_e572kWh_p150kW_eta98.csv"
