[simulation]
name = "f5_h02"
start = "2026-01-07 20:45"
end = "2026-03-25 23:45"

[optimization.mpc]
id_horizon_hours = 2

[optimization.flexibility]
bounds_file = "data/flexibility/market/VBbounds_f5_e572kWh_p150kW_eta98.csv"
